
table users{
  id bigserial [primary key]
  username varchar(60) [unique]
  fullname varchar(80)
  password varchar(500)
}

table sessions{
  id bigserial [primary key]
  token varchar(1000) [unique]
  create_at date
  update_at date
  state boolean
  id_user bigint
}

table user_info{
  id bigserial [primary key]
  id_user bigint
  description varchar(300)
  urlImage varchar(500)
  imagefilename varchar(255)
  born date
  create_count date
}

table imagenes{
  id bigserial [primary key]
  url_image varchar(555)
  imagefilename varchar(255) [unique]
  description varchar(255)
  id_user bidint
  create_at date
}

table likes{
  id bigserial [primary key]
  create_at date
  id_image bigint
  id_user bigint 
}

table comentarios{
  id bigserial [primary key]
  create_at date
  comment varchar(255)
  id_image bigint
  id_user bigint 
}

table roles{
  id bigserial [primary key]
  name varchar(10) [unique]
}

table user_roles{
  id_user bigint
  id_role bigint
}

Ref : users.id - user_info.id_user
Ref : imagenes.id_user > users.id
Ref : likes.id_image > imagenes.id
Ref : likes.id_user > users.id
Ref : comentarios.id_user > users.id
Ref : comentarios.id_image > imagenes.id
Ref : users.id <> user_roles.id_user
Ref : roles.id <> user_roles.id_role
Ref : sessions.id_user > users.id
